// <copyright file="AcceptanceTestEmitter.cs" company="AiOrchestrator contributors">
// Copyright (c) AiOrchestrator contributors. All rights reserved.
// </copyright>

using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace AiOrchestrator.Eventing.Generators;

/// <summary>Emits <c>EventVersionAcceptanceTests.g.cs</c> as xUnit test methods.</summary>
internal sealed class AcceptanceTestEmitter
{
    /// <summary>Emits the acceptance test source file.</summary>
    /// <param name="versions">All discovered versions in the compilation.</param>
    /// <returns>Generated C# source.</returns>
    public string Emit(IReadOnlyList<EventVersionInfo> versions)
    {
        if (versions == null) return string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("namespace AiOrchestrator.Eventing.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    using System;");
        sb.AppendLine("    using System.Collections.Generic;");
        sb.AppendLine("    using System.IO;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Per-version round-trip descriptors emitted for every released [EventV] type.");
        sb.AppendLine("    /// Tests in the consuming project iterate this list and assert each captured");
        sb.AppendLine("    /// wire-format payload deserializes and migrates through to the latest version");
        sb.AppendLine("    /// without data loss. Fixtures live under tests/dotnet/EventVersioning.Fixtures.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal static class EventVersionAcceptanceCases");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>A single round-trip case: an event-type/version pair plus the relative fixture path.</summary>");
        sb.AppendLine("        public readonly struct Case");
        sb.AppendLine("        {");
        sb.AppendLine("            public Case(string eventTypeName, int version, int latestVersion, Type type, string fixtureRelativePath)");
        sb.AppendLine("            {");
        sb.AppendLine("                EventTypeName = eventTypeName;");
        sb.AppendLine("                Version = version;");
        sb.AppendLine("                LatestVersion = latestVersion;");
        sb.AppendLine("                Type = type;");
        sb.AppendLine("                FixtureRelativePath = fixtureRelativePath;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            public string EventTypeName { get; }");
        sb.AppendLine("            public int Version { get; }");
        sb.AppendLine("            public int LatestVersion { get; }");
        sb.AppendLine("            public Type Type { get; }");
        sb.AppendLine("            public string FixtureRelativePath { get; }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>All cases discovered at compile time.</summary>");
        sb.AppendLine("        public static readonly IReadOnlyList<Case> All = BuildAll();");
        sb.AppendLine();
        sb.AppendLine("        private static IReadOnlyList<Case> BuildAll()");
        sb.AppendLine("        {");
        sb.AppendLine("            var list = new List<Case>();");

        var byName = versions
            .GroupBy(v => v.EventTypeName, System.StringComparer.Ordinal)
            .OrderBy(g => g.Key, System.StringComparer.Ordinal);
        foreach (var group in byName)
        {
            var ordered = group.OrderBy(v => v.Version).ToList();
            int latest = ordered[ordered.Count - 1].Version;
            foreach (var v in ordered)
            {
                sb.Append("            list.Add(new Case(\"")
                  .Append(Escape(v.EventTypeName))
                  .Append("\", ")
                  .Append(v.Version.ToString(CultureInfo.InvariantCulture))
                  .Append(", ")
                  .Append(latest.ToString(CultureInfo.InvariantCulture))
                  .Append(", typeof(")
                  .Append(v.FullyQualifiedTypeName)
                  .Append("), \"")
                  .Append(Escape(v.EventTypeName))
                  .Append("/v")
                  .Append(v.Version.ToString(CultureInfo.InvariantCulture))
                  .AppendLine(".json\"));");
            }
        }

        sb.AppendLine("            return list;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Escape(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
