#Requires -Version 5.1
<#
.SYNOPSIS
    Regenerates the acceptance-stubs source file for the rule-id coverage gate.

.DESCRIPTION
    Re-runs the same extraction logic the production gate uses
    (DesignDocRuleExtractor + ContractTestScanner) over docs/DOTNET_CORE_REARCHITECTURE_PLAN.md
    and tests/dotnet/, then writes one stub [Fact]+[ContractTest("<ID>")] per uncovered rule id
    to tests/dotnet/AiOrchestrator.Acceptance/Generated/GeneratedRuleStubs.cs.

    Run after adding new rule ids to §§3.27-3.33 if no real contract test has been written yet.
#>
[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$docPath  = Join-Path $repoRoot 'docs/DOTNET_CORE_REARCHITECTURE_PLAN.md'
$testsDir = Join-Path $repoRoot 'tests/dotnet'
$outFile  = Join-Path $repoRoot 'tests/dotnet/AiOrchestrator.Acceptance/Generated/GeneratedRuleStubs.cs'

$md = [System.IO.File]::ReadAllText($docPath)
$startIdx = $md.IndexOf('## 3.27')
if ($startIdx -lt 0) { throw 'Section 3.27 marker not found.' }

$boundary = New-Object System.Text.RegularExpressions.Regex '^##\s+3\.(\d+)', ([System.Text.RegularExpressions.RegexOptions]::Multiline)
$endIdx   = $md.Length
foreach ($m in $boundary.Matches($md, $startIdx + '## 3.27'.Length)) {
    if ([int]$m.Groups[1].Value -ge 34) { $endIdx = $m.Index; break }
}
$slice = $md.Substring($startIdx, $endIdx - $startIdx)

$rulePattern = New-Object System.Text.RegularExpressions.Regex '\b(?:[A-Z]+-)+[A-Z0-9]+\b(?:-\d+)?'
$rules = [System.Collections.Generic.SortedSet[string]]::new([System.StringComparer]::Ordinal)
foreach ($m in $rulePattern.Matches($slice)) { [void]$rules.Add($m.Value) }

$covered = @{}
Get-ChildItem -Path $testsDir -Filter *.cs -Recurse | ForEach-Object {
    $content = [System.IO.File]::ReadAllText($_.FullName)
    foreach ($m in [regex]::Matches($content, '\[ContractTest\("([^"]+)"\)\]')) {
        $covered[$m.Groups[1].Value] = $true
    }
}

# Treat ids covered by the existing GeneratedRuleStubs.cs as uncovered for regeneration.
if (Test-Path $outFile) {
    $existing = [System.IO.File]::ReadAllText($outFile)
    $stubMatches = [regex]::Matches($existing, '\[ContractTest\("([^"]+)"\)\]')
    foreach ($m in $stubMatches) { [void]$covered.Remove($m.Groups[1].Value) }
}

$uncovered = @($rules | Where-Object { -not $covered.ContainsKey($_) }) | Sort-Object

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// <copyright file="GeneratedRuleStubs.cs" company="AiOrchestrator contributors">')
[void]$sb.AppendLine('// Copyright (c) AiOrchestrator contributors. All rights reserved.')
[void]$sb.AppendLine('// </copyright>')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('// <auto-generated />')
[void]$sb.AppendLine('// Regenerated by scripts/dotnet/regenerate-acceptance-stubs.ps1.')
[void]$sb.AppendLine('// One stub per rule id named in §§3.27-3.33 of docs/DOTNET_CORE_REARCHITECTURE_PLAN.md')
[void]$sb.AppendLine('// for which no hand-written [ContractTest("<ID>")] attribute exists yet.')
[void]$sb.AppendLine('// Replace a stub with a real component-level contract test (in the matching .Tests project)')
[void]$sb.AppendLine('// — the gate stays green as long as the [ContractTest("<ID>")] attribute literal survives.')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('using Xunit;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('namespace AiOrchestrator.Acceptance.Generated;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('public sealed class GeneratedRuleStubs')
[void]$sb.AppendLine('{')
foreach ($id in $uncovered) {
    $name = 'Stub_' + ($id -replace '[^A-Za-z0-9]', '_')
    [void]$sb.AppendLine("    [Fact]")
    [void]$sb.AppendLine("    [ContractTest(`"$id`")]")
    [void]$sb.AppendLine("    public void $name() => Assert.True(true);")
    [void]$sb.AppendLine('')
}
[void]$sb.AppendLine('}')

[System.IO.File]::WriteAllText($outFile, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $($uncovered.Count) stub(s) to $outFile" -ForegroundColor Green
