/**
 * @fileoverview PR Lifecycle Types
 *
 * Defines types for PR lifecycle management, including PR adoption, monitoring,
 * status tracking, and promotion/demotion operations.
 *
 * @module plan/types/prLifecycle
 */

import type { RemoteProviderType } from './remotePR';

// ============================================================================
// PR LIFECYCLE ACTIONS
// ============================================================================

/**
 * Actions that can be performed on a managed PR.
 * 
 * - `adopt`: Take ownership of an existing PR for monitoring
 * - `monitor`: Start automated monitoring of PR status
 * - `promote`: Elevate a PR to a higher priority tier
 * - `demote`: Lower a PR to a lower priority tier
 * - `abandon`: Stop managing a PR without deleting it
 * - `remove`: Completely remove a PR from management
 */
export type PRLifecycleAction = 
  | 'adopt' 
  | 'monitor' 
  | 'promote' 
  | 'demote' 
  | 'abandon' 
  | 'remove';

// ============================================================================
// PR STATUS
// ============================================================================

/**
 * Status of a managed pull request.
 * 
 * - `adopted`: PR has been adopted but monitoring has not started
 * - `monitoring`: Actively monitoring PR for checks, comments, and alerts
 * - `addressing`: Autonomously addressing PR feedback
 * - `ready`: All checks passed, ready to merge
 * - `blocked`: PR is blocked by failing checks or unresolved feedback
 * - `abandoned`: PR management has been stopped
 */
export type ManagedPRStatus = 
  | 'adopted' 
  | 'monitoring' 
  | 'addressing' 
  | 'ready' 
  | 'blocked' 
  | 'abandoned';

// ============================================================================
// MANAGED PR
// ============================================================================

/**
 * A pull request under lifecycle management.
 * 
 * Represents a PR that has been adopted for monitoring and autonomous
 * feedback handling. The PR may originate from a release or be adopted
 * from an existing external PR.
 */
export interface ManagedPR {
  /** Unique identifier for the managed PR (generated by PR lifecycle manager) */
  id: string;

  /** PR number assigned by the remote provider */
  prNumber: number;

  /** Full URL to the PR */
  prUrl: string;

  /** Title of the PR */
  title: string;

  /** Base branch (target) for the PR */
  baseBranch: string;

  /** Head branch (source) containing the changes */
  headBranch: string;

  /** Current lifecycle status */
  status: ManagedPRStatus;

  /** Remote provider type (from remotePR.ts) */
  providerType: RemoteProviderType;

  /** Repository path where the PR originates */
  repoPath: string;

  /** Working directory for PR operations (may be an isolated clone) */
  workingDirectory: string;

  /** Optional associated release ID if this PR came from a release */
  releaseId?: string;

  /** Optional priority tier (higher = more important) */
  priority?: number;

  /** Timestamp when PR was adopted */
  adoptedAt: number;

  /** Timestamp when monitoring started */
  monitoringStartedAt?: number;

  /** Timestamp when PR reached ready/blocked/abandoned state */
  completedAt?: number;

  /** Number of unresolved comments */
  unresolvedComments?: number;

  /** Number of failing checks */
  failingChecks?: number;

  /** Number of unresolved security alerts */
  unresolvedAlerts?: number;

  /** Error message if PR management failed */
  error?: string;
}

// ============================================================================
// ADOPT PR
// ============================================================================

/**
 * Options for adopting an existing pull request.
 */
export interface AdoptPROptions {
  /** PR number to adopt */
  prNumber: number;

  /** Repository path where the PR exists */
  repoPath: string;

  /** Optional working directory for PR operations (defaults to repoPath) */
  workingDirectory?: string;

  /** Optional associated release ID */
  releaseId?: string;

  /** Optional priority tier (defaults to 0) */
  priority?: number;
}

/**
 * Result of adopting a pull request.
 */
export interface AdoptPRResult {
  /** Whether the PR was successfully adopted */
  success: boolean;

  /** The adopted PR definition if successful */
  managedPR?: ManagedPR;

  /** Error message if adoption failed */
  error?: string;
}

// ============================================================================
// LIST PRS
// ============================================================================

/**
 * Options for listing available pull requests.
 */
export interface ListPRsOptions {
  /** Repository path to list PRs from */
  repoPath: string;

  /** Optional filter by base branch */
  baseBranch?: string;

  /** Optional filter by PR state (default: 'open') */
  state?: 'open' | 'closed' | 'all';

  /** Optional limit on number of results (default: 30) */
  limit?: number;
}

/**
 * A pull request available for adoption.
 * 
 * Lightweight representation of a PR that exists on the remote provider
 * but is not yet under lifecycle management.
 */
export interface AvailablePR {
  /** PR number */
  prNumber: number;

  /** PR title */
  title: string;

  /** Base branch (target) */
  baseBranch: string;

  /** Head branch (source) */
  headBranch: string;

  /** Author username */
  author: string;

  /** PR state (open, closed, merged) */
  state: string;

  /** Full URL to the PR */
  url: string;

  /** Whether this PR is already managed */
  isManaged: boolean;
}

// ============================================================================
// OPERATION RESULTS
// ============================================================================

/**
 * Result of a PR lifecycle operation.
 * 
 * Generic result type for operations like promote, demote, abandon, remove.
 */
export interface PRLifecycleResult {
  /** Whether the operation succeeded */
  success: boolean;

  /** Optional result message */
  message?: string;

  /** Error message if operation failed */
  error?: string;
}
