/**
 * @fileoverview Re-export N-API binding types from bindings/node/src/index.ts.
 *
 * The bindings live outside src/ (in bindings/node/) so they can't be imported
 * directly without widening rootDir. This declaration file mirrors the types
 * so that src/transport/dotnetTransport.ts can import them normally.
 *
 * Keep in sync with bindings/node/src/index.ts (auto-generated by DtsGenerator).
 */

export interface AioOrchestrator {
  createPlan(options: CreatePlanOptions): Promise<PlanHandle>;
  resolvePlan(planId: string): Promise<PlanHandle>;
  listPlans(): AsyncIterable<PlanSummary>;
}

export interface PlanHandle extends AsyncDisposable {
  readonly planId: string;
  addJob(spec: JobSpec): Promise<JobHandle>;
  finalize(): Promise<void>;
  status(): Promise<PlanStatus>;
  watch(): AsyncIterable<PlanEvent>;
  cancel(): Promise<void>;
}

export interface JobHandle extends AsyncDisposable {
  readonly jobId: string;
  readonly producerId: string;
}

export interface CreatePlanOptions {
  readonly name: string;
}

export interface PlanSummary {
  readonly planId: string;
  readonly state: string;
}

export interface JobSpec {
  readonly producerId: string;
}

export interface PlanStatus {
  readonly state: string;
}

export interface PlanEvent {
  readonly kind: string;
}

export interface AioError extends Error {
  readonly code: string;
}
