// <copyright file="MigrationTableEmitter.cs" company="AiOrchestrator contributors">
// Copyright (c) AiOrchestrator contributors. All rights reserved.
// </copyright>

using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace AiOrchestrator.Eventing.Generators;

/// <summary>Emits <c>EventTypeRegistry.g.cs</c> and <c>EventMigrationGraph.g.cs</c>.</summary>
internal sealed class MigrationTableEmitter
{
    /// <summary>Emits the registry source file.</summary>
    /// <param name="versions">All discovered <c>[EventV]</c>-attributed types in the compilation.</param>
    /// <returns>Generated C# source.</returns>
    public string Emit(IReadOnlyList<EventVersionInfo> versions)
    {
        if (versions == null) return string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("namespace AiOrchestrator.Eventing.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    using System;");
        sb.AppendLine("    using System.Collections.Generic;");
        sb.AppendLine("    using System.Collections.ObjectModel;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Compile-time registry mapping (eventTypeName, version) -> Type. Frozen at startup.</summary>");
        sb.AppendLine("    internal static class EventTypeRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        private static readonly IReadOnlyDictionary<(string EventTypeName, int Version), Type> _map = BuildMap();");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Gets the immutable (eventTypeName, version) -> Type map.</summary>");
        sb.AppendLine("        public static IReadOnlyDictionary<(string EventTypeName, int Version), Type> Map => _map;");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Tries to resolve an event type for the given discriminator pair.</summary>");
        sb.AppendLine("        public static bool TryResolve(string eventTypeName, int version, out Type? type)");
        sb.AppendLine("        {");
        sb.AppendLine("            return _map.TryGetValue((eventTypeName, version), out type!);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private static IReadOnlyDictionary<(string EventTypeName, int Version), Type> BuildMap()");
        sb.AppendLine("        {");
        sb.AppendLine("            var d = new Dictionary<(string, int), Type>(" + versions.Count.ToString(CultureInfo.InvariantCulture) + ");");
        foreach (var v in versions.OrderBy(x => x.EventTypeName, System.StringComparer.Ordinal).ThenBy(x => x.Version))
        {
            sb.Append("            d[(\"")
              .Append(Escape(v.EventTypeName))
              .Append("\", ")
              .Append(v.Version.ToString(CultureInfo.InvariantCulture))
              .Append(")] = typeof(")
              .Append(v.FullyQualifiedTypeName)
              .AppendLine(");");
        }

        sb.AppendLine("            return new ReadOnlyDictionary<(string, int), Type>(d);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>Emits the migration graph source file.</summary>
    /// <param name="versions">All discovered versions.</param>
    /// <returns>Generated C# source.</returns>
    public string EmitGraph(IReadOnlyList<EventVersionInfo> versions)
    {
        if (versions == null) return string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("namespace AiOrchestrator.Eventing.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    using System;");
        sb.AppendLine("    using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Compile-time migration graph. Each adjacent (N, N+1) edge is verified by the");
        sb.AppendLine("    /// generator; missing edges fail the build with diagnostic EVGEN001.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal static class EventMigrationGraph");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Edges in the migration graph: (eventTypeName, fromVersion) -> toVersion.</summary>");
        sb.AppendLine("        public static readonly IReadOnlyList<(string EventTypeName, int FromVersion, int ToVersion)> Edges = new (string, int, int)[]");
        sb.AppendLine("        {");

        var byName = versions
            .GroupBy(v => v.EventTypeName, System.StringComparer.Ordinal)
            .OrderBy(g => g.Key, System.StringComparer.Ordinal);
        foreach (var group in byName)
        {
            var ordered = group.OrderBy(v => v.Version).ToList();
            for (int i = 0; i + 1 < ordered.Count; i++)
            {
                sb.Append("            (\"")
                  .Append(Escape(group.Key))
                  .Append("\", ")
                  .Append(ordered[i].Version.ToString(CultureInfo.InvariantCulture))
                  .Append(", ")
                  .Append(ordered[i + 1].Version.ToString(CultureInfo.InvariantCulture))
                  .AppendLine("),");
            }
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Escape(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
