// <auto-generated />
// Regenerated from the .NET public surface by DtsGenerator; do not edit by hand.
//
// AiOrchestrator.Bindings.Node — N-API bindings (§3.17 / job 036).
// INV-1..INV-3: every .NET object exposed to Node lives behind an opaque handle.
// INV-5:        async iterators map to Node's AsyncIterator protocol.
// INV-6:        this declaration file is generated; keep it in sync with .NET.
// INV-7:        N-API version 8 (Node 16+ LTS).
// INV-8:        errors carry a `code` field matching the .NET exception name.

export interface AioOrchestrator {
    createPlan(options: CreatePlanOptions): Promise<PlanHandle>;
    resolvePlan(planId: string): Promise<PlanHandle>;
    listPlans(): AsyncIterable<PlanSummary>;
}

export interface PlanHandle extends AsyncDisposable {
    readonly planId: string;
    addJob(spec: JobSpec): Promise<JobHandle>;
    finalize(): Promise<void>;
    status(): Promise<PlanStatus>;
    watch(): AsyncIterable<PlanEvent>;
    cancel(): Promise<void>;
}

export interface JobHandle extends AsyncDisposable {
    readonly jobId: string;
    readonly producerId: string;
}

export interface CreatePlanOptions {
    readonly name: string;
}

export interface PlanSummary {
    readonly planId: string;
    readonly state: string;
}

export interface JobSpec {
    readonly producerId: string;
}

export interface PlanStatus {
    readonly state: string;
}

export interface PlanEvent {
    readonly kind: string;
}

export interface AioError extends Error {
    readonly code: string;
}
