"use strict";
// <auto-generated />
// Regenerated from the .NET public surface by DtsGenerator; do not edit by hand.
//
// AiOrchestrator.Bindings.Node — N-API bindings (§3.17 / job 036).
// INV-1..INV-3: every .NET object exposed to Node lives behind an opaque handle.
// INV-5:        async iterators map to Node's AsyncIterator protocol.
// INV-6:        this declaration file is generated; keep it in sync with .NET.
// INV-7:        N-API version 8 (Node 16+ LTS).
// INV-8:        errors carry a `code` field matching the .NET exception name.
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=index.js.map