/**
 * @fileoverview IPRLifecycleManager Interface
 *
 * Manages the lifecycle of pull requests, including adoption, monitoring,
 * promotion/demotion, and autonomous feedback handling.
 *
 * @module interfaces/IPRLifecycleManager
 */

import type {
  ManagedPR,
  ManagedPRStatus,
  AdoptPROptions,
  AdoptPRResult,
  ListPRsOptions,
  AvailablePR,
  PRLifecycleResult,
} from '../plan/types/prLifecycle';

/**
 * PR Lifecycle Manager interface.
 * 
 * Orchestrates the lifecycle of pull requests by:
 * 1. Discovering and listing available PRs from remote providers
 * 2. Adopting existing PRs for management
 * 3. Monitoring PR status (checks, comments, security alerts)
 * 4. Autonomously addressing PR feedback
 * 5. Managing PR priority and lifecycle transitions
 * 
 * This service works alongside IReleaseManager to provide unified PR
 * management for both release-generated PRs and externally-created PRs.
 * 
 * @example
 * ```typescript
 * const prManager = container.resolve<IPRLifecycleManager>(Tokens.IPRLifecycleManager);
 * 
 * // List available PRs
 * const available = await prManager.listAvailablePRs({
 *   repoPath: '/path/to/repo',
 *   baseBranch: 'main',
 *   state: 'open',
 * });
 * 
 * // Adopt a PR for management
 * const result = await prManager.adoptPR({
 *   prNumber: 42,
 *   repoPath: '/path/to/repo',
 *   priority: 1,
 * });
 * 
 * // Start monitoring
 * await prManager.startMonitoring(result.managedPR.id);
 * 
 * // Later: promote to higher priority
 * await prManager.promotePR(result.managedPR.id);
 * ```
 */
export interface IPRLifecycleManager {
  // ── PR Discovery ───────────────────────────────────────────────────

  /**
   * Lists available pull requests from the remote provider.
   * 
   * Retrieves PRs that exist on the remote but may or may not be under
   * lifecycle management. Results include an `isManaged` flag to indicate
   * whether each PR is already being managed.
   * 
   * @param options - Filtering and pagination options
   * @returns Array of available PRs with metadata
   * @throws If the repository or remote provider cannot be accessed
   */
  listAvailablePRs(options: ListPRsOptions): Promise<AvailablePR[]>;

  // ── PR Adoption ────────────────────────────────────────────────────

  /**
   * Adopts an existing pull request for lifecycle management.
   * 
   * Takes ownership of an existing PR, creating a ManagedPR record.
   * The PR transitions to 'adopted' status and can then be monitored.
   * 
   * @param options - PR adoption parameters
   * @returns Result containing the managed PR definition or error
   * @throws If the PR does not exist or has already been adopted
   */
  adoptPR(options: AdoptPROptions): Promise<AdoptPRResult>;

  // ── PR Queries ─────────────────────────────────────────────────────

  /**
   * Gets a managed PR by its lifecycle manager ID.
   * 
   * @param id - The managed PR ID (generated by lifecycle manager)
   * @returns The managed PR or undefined if not found
   */
  getManagedPR(id: string): ManagedPR | undefined;

  /**
   * Gets a managed PR by its provider-assigned PR number.
   * 
   * @param prNumber - The PR number
   * @param repoPath - Repository path to disambiguate across repos
   * @returns The managed PR or undefined if not found
   */
  getManagedPRByNumber(prNumber: number, repoPath: string): ManagedPR | undefined;

  /**
   * Gets all managed PRs.
   * 
   * @returns Array of all managed PRs
   */
  getAllManagedPRs(): ManagedPR[];

  /**
   * Gets managed PRs by status.
   * 
   * @param status - The PR status to filter by
   * @returns Array of matching managed PRs
   */
  getManagedPRsByStatus(status: ManagedPRStatus): ManagedPR[];

  // ── PR Monitoring ──────────────────────────────────────────────────

  /**
   * Starts monitoring a managed PR.
   * 
   * Transitions the PR from 'adopted' to 'monitoring' and begins periodic
   * polling for CI checks, comments, and security alerts. Autonomous feedback
   * handling is enabled.
   * 
   * @param id - The managed PR ID
   * @throws If the PR is not found or is not in 'adopted' status
   */
  startMonitoring(id: string): Promise<void>;

  /**
   * Stops monitoring a managed PR.
   * 
   * Halts periodic polling and autonomous feedback handling without
   * abandoning the PR. The PR remains in the managed list but transitions
   * to 'adopted' status.
   * 
   * @param id - The managed PR ID
   * @throws If the PR is not found or is not in 'monitoring' or 'addressing' status
   */
  stopMonitoring(id: string): Promise<void>;

  // ── PR Lifecycle Management ────────────────────────────────────────

  /**
   * Abandons a managed PR.
   * 
   * Stops all monitoring and transitions the PR to 'abandoned' status.
   * The PR remains in the managed list for historical records but is
   * no longer actively managed.
   * 
   * @param id - The managed PR ID
   * @returns Result indicating success or failure
   */
  abandonPR(id: string): Promise<PRLifecycleResult>;

  /**
   * Promotes a managed PR to a higher priority tier.
   * 
   * Increases the PR's priority value, potentially affecting scheduling
   * and monitoring frequency.
   * 
   * @param id - The managed PR ID
   * @returns Result indicating success or failure
   */
  promotePR(id: string): Promise<PRLifecycleResult>;

  /**
   * Demotes a managed PR to a lower priority tier.
   * 
   * Decreases the PR's priority value, potentially affecting scheduling
   * and monitoring frequency.
   * 
   * @param id - The managed PR ID
   * @returns Result indicating success or failure
   */
  demotePR(id: string): Promise<PRLifecycleResult>;

  /**
   * Removes a managed PR from the lifecycle manager.
   * 
   * Completely removes the PR from management. This is typically used
   * for cleanup after a PR has been merged or closed externally.
   * 
   * @param id - The managed PR ID
   * @returns Result indicating success or failure
   */
  removePR(id: string): Promise<PRLifecycleResult>;

  // ── Events ─────────────────────────────────────────────────────────

  /**
   * Registers an event handler.
   * 
   * @param event - The event name
   * @param handler - The event handler function
   */
  on(event: 'prAdopted', handler: (pr: ManagedPR) => void): void;
  on(event: 'prStatusChanged', handler: (pr: ManagedPR) => void): void;
  on(event: 'prMonitoringStarted', handler: (pr: ManagedPR) => void): void;
  on(event: 'prMonitoringStopped', handler: (pr: ManagedPR) => void): void;
  on(event: 'prAbandoned', handler: (pr: ManagedPR) => void): void;
  on(event: 'prRemoved', handler: (id: string) => void): void;
  on(event: 'prPromoted', handler: (pr: ManagedPR) => void): void;
  on(event: 'prDemoted', handler: (pr: ManagedPR) => void): void;
}
