// <copyright file="DtsGenerator.cs" company="AiOrchestrator contributors">
// Copyright (c) AiOrchestrator contributors. All rights reserved.
// </copyright>

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Text;

namespace AiOrchestrator.Bindings.Node.Generators;

/// <summary>
/// Build-time helper that emits a TypeScript declaration (<c>.d.ts</c>) file
/// from a set of .NET types. The generator walks public members and maps
/// canonical primitive + task types to their TypeScript equivalents.
/// </summary>
public sealed class DtsGenerator
{
    /// <summary>Generates a <c>.d.ts</c> declaration file for the supplied types.</summary>
    /// <param name="types">The types to expose.</param>
    /// <returns>The TypeScript declaration content.</returns>
    public static string Generate(IReadOnlyList<Type> types)
    {
        ArgumentNullException.ThrowIfNull(types);

        StringBuilder sb = new();
        _ = sb.AppendLine("// <auto-generated />");
        _ = sb.AppendLine("// DtsGenerator: do not edit this file by hand.");
        _ = sb.AppendLine();

        foreach (Type type in types.OrderBy(t => t.FullName, StringComparer.Ordinal))
        {
            _ = sb.Append("export interface ")
                  .Append(type.Name)
                  .AppendLine(" {");

            foreach (PropertyInfo property in type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
                                                  .OrderBy(p => p.Name, StringComparer.Ordinal))
            {
                _ = sb.Append("    ")
                      .Append(ToCamelCase(property.Name))
                      .Append(": ")
                      .Append(MapType(property.PropertyType))
                      .AppendLine(";");
            }

            foreach (MethodInfo method in type.GetMethods(BindingFlags.Public | BindingFlags.Instance)
                                              .Where(IsExportableMethod)
                                              .OrderBy(m => m.Name, StringComparer.Ordinal))
            {
                _ = sb.Append("    ")
                      .Append(ToCamelCase(method.Name));

                ParameterInfo[] parameters = method.GetParameters();
                _ = sb.Append('(');
                for (int i = 0; i < parameters.Length; i++)
                {
                    if (i > 0)
                    {
                        _ = sb.Append(", ");
                    }

                    _ = sb.Append(parameters[i].Name)
                          .Append(": ")
                          .Append(MapType(parameters[i].ParameterType));
                }

                _ = sb.Append("): ")
                      .Append(MapType(method.ReturnType))
                      .AppendLine(";");
            }

            _ = sb.AppendLine("}");
            _ = sb.AppendLine();
        }

        return sb.ToString();
    }

    private static bool IsExportableMethod(MethodInfo method)
    {
        if (method.IsSpecialName)
        {
            return false;
        }

        if (method.DeclaringType == typeof(object))
        {
            return false;
        }

        return !method.Name.StartsWith("get_", StringComparison.Ordinal)
            && !method.Name.StartsWith("set_", StringComparison.Ordinal);
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }

        return string.Concat(char.ToLowerInvariant(name[0]).ToString(CultureInfo.InvariantCulture), name.AsSpan(1));
    }

    private static string MapType(Type type)
    {
        if (type == typeof(void))
        {
            return "void";
        }

        if (type == typeof(string))
        {
            return "string";
        }

        if (type == typeof(bool))
        {
            return "boolean";
        }

        if (type == typeof(int) || type == typeof(long) || type == typeof(double) || type == typeof(float))
        {
            return "number";
        }

        if (type == typeof(byte[]))
        {
            return "Uint8Array";
        }

        if (type.IsGenericType)
        {
            Type def = type.GetGenericTypeDefinition();
            Type arg = type.GetGenericArguments()[0];
            if (def == typeof(System.Threading.Tasks.Task<>) || def == typeof(System.Threading.Tasks.ValueTask<>))
            {
                return "Promise<" + MapType(arg) + ">";
            }

            if (def == typeof(System.Collections.Generic.IAsyncEnumerable<>))
            {
                return "AsyncIterable<" + MapType(arg) + ">";
            }
        }

        if (type == typeof(System.Threading.Tasks.Task) || type == typeof(System.Threading.Tasks.ValueTask))
        {
            return "Promise<void>";
        }

        return type.Name;
    }
}
